Repository microsoft/BackwardCompatibilityML, pull requests merged in 2020-11, with the labels that each got.

#51 Show incompatible points in histogram
  backwardcompatibilityml/helpers/training.py
  widget/IncompatiblePointDistribution.tsx
Labels: bug

#61 Add statefulness to selectivity of the regions of the Venn diagram, and calculate the percentage of errors out of the total number of instances
  backwardcompatibilityml/helpers/training.py
  widget/IntersectionBetweenModelErrors.tsx
Labels: enhancement

#60 Histogram - highlight column on click with CSS style
  widget/IncompatiblePointDistribution.tsx
  widget/widget.css
Labels: enhancement

#67 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation

#65 Docs update new loss functions and examples
  backwardcompatibilityml/helpers/training.py
  backwardcompatibilityml/loss/new_error.py
  backwardcompatibilityml/loss/strict_imitation.py
  backwardcompatibilityml/sweep_management.py
  backwardcompatibilityml/widget/compatibility_analysis.py
  docs/backwardcompatibilityml/topics/examples.csv
  docs/backwardcompatibilityml/topics/integrating_loss_functions.rst
  docs/source/backwardcompatibilityml.helpers.rst
  docs/source/backwardcompatibilityml.rst
Labels: documentation

#69 Add cases for Venn diagram to deal with disjoint h1 and h2 error sets and total intersection
  widget/IncompatiblePointDistribution.tsx
  widget/IntersectionBetweenModelErrors.tsx
Labels: bug

#72 Make sure to reset the filter to null between selection of data points
  widget/reducers.ts
Labels: bug

#63 Dev harness style fixes
  development/app.py
  development/index.html
  widget/widget.css
Labels: bug

#78 Clickable legend in Venn diagram and removing the warnings in the example notebooks
  examples/bckldivergence.ipynb
  examples/bcnllloss.ipynb
  examples/si_cross_entropy_loss.ipynb
  examples/si_nllloss.ipynb
  widget/IntersectionBetweenModelErrors.tsx
Labels: enhancement

#77 Dev harness fix - IndexError: list index out of range when running MNIST sweep
  development/app.py
Labels: bug

#80 Style error table pagination buttons like the histogram buttons
  widget/ErrorInstancesTable.tsx
Labels: enhancement
