Repository microsoft/BackwardCompatibilityML, pull requests merged in 2020-12, with the labels that each got.

#81 Info tooltips
  widget/IncompatiblePointDistribution.tsx
  widget/InfoTooltip.tsx
  widget/IntersectionBetweenModelErrors.tsx
  widget/MainContainer.tsx
  widget/PerformanceCompatibility.tsx
  widget/VennLegend.tsx
  widget/actions.ts
  widget/index.tsx
  widget/reducers.ts
  widget/widget.css
Labels: enhancement

#84 Documentation for using the widget
  docs/backwardcompatibilityml/media/compatibility_analysis_widget.png
  docs/backwardcompatibilityml/media/error_instances_table.png
  docs/backwardcompatibilityml/topics/using_the_compatibility_analysis_widget.rst
Labels: documentation

#85 Implement a Backward Compatibility New Error Model for training Tensorflow models using the BC New Error Loss
  backwardcompatibilityml/tensorflow/__init__.py
  backwardcompatibilityml/tensorflow/helpers.py
  backwardcompatibilityml/tensorflow/loss/__init__.py
  backwardcompatibilityml/tensorflow/loss/new_error.py
  backwardcompatibilityml/tensorflow/models.py
  examples/tensorflow-MNIST-generalized.ipynb
  examples/tensorflow-MNIST.ipynb
  requirements.txt
Labels: enhancement

#90 Integrate MLflow; allow multiple sweeps
  .gitignore
  README.md
  backwardcompatibilityml/helpers/training.py
  backwardcompatibilityml/sweep_management.py
  backwardcompatibilityml/widget/compatibility_analysis.py
  development/app.py
  requirements.txt
  widget/SweepManager.tsx
  widget/actions.ts
Labels: bug, enhancement
